host: localhost:50051
auth-key: authkey
signin-key: signkey
db:
  host: localhost
  user: postgres
  pass: postgres
  db_name: dummydb
  db_port: 5432
tls:
  enabled: true
  certfile: ./tests/certs/localhost_50051.crt
  certkey: ./tests/certs/localhost_50051.key
  cafile: ./tests/certs/haaukins-store.com.crt