version: '3'
services:
  server:
    container_name: server
    build: .
    ports:
      - "50051:50051"
    restart: on-failure
    depends_on:
      - postgres-db
    volumes:
      - ${CONFIG_PATH}:/config.yml:ro  # mount config file
    networks:
      - internal

  postgres-db:
    image: postgres:alpine
    container_name: postgres
    command: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # database name
      POSTGRES_USER: ${POSTGRES_USER} # database user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # database password
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - internal

# Networks to be created to facilitate communication between containers
volumes:
  data:
networks:
  internal:
    driver: bridge
