version: '3'
services:
  server_test:
    container_name: server_test
    env_file:
      - .env_test
    build:
      context: .
      dockerfile: Dockerfile.tests
    ports:
      - 50051:50051
    depends_on:
      - postgres_test
    volumes:
      - ${CERTS_PATH}:/certs:ro
    networks:
      - internal_test

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    env_file:
      - .env_test
    ports:
      - '5432:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - internal_test

volumes:
  database_postgres_test:

# Networks to be created to facilitate communication between containers
networks:
  internal_test:
    driver: bridge
