version: '3'
services:
  server:
    container_name: server
    env_file:
      - .env
    build: .
    ports:
      - 50051:50051
    restart: on-failure
    depends_on:
      - postgres-db
    volumes:
      - ${CERTS_PATH}:/certs:ro
    networks:
      - internal


  postgres-db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file:
      - .env
    depends_on:
      - postgres-db
    ports:
      - "5050:443"
    volumes: 
      - ${CERTS_PATH}/cli2.sec-aau.dk/fullchain.pem:/certs/server.cert
      - ${CERTS_PATH}/cli2.sec-aau.dk/privkey.pem:/certs/server.key
    networks:
      - internal
    restart: unless-stopped

volumes:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  internal:
    driver: bridge
