version: '3'
services:
  server:
    container_name: server
    env_file:
      - .env
    build: .
    ports:
      - 50051:50051
    restart: on-failure
    depends_on:
      - postgres-db
    volumes:
      - ${CERTS_PATH}:/certs:ro  # in production, change this CERTS_PATH to your certificate files folder
      - ${CONFIG_PATH}:/config.yml:ro  # mount config file
    networks:
      - internal

  postgres-db:
    image: postgres:alpine
    container_name: postgres
    command: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ${PSQL_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - internal

# Networks to be created to facilitate communication between containers
volumes:
  data:
networks:
  internal:
    driver: bridge
