version: '3'
services:
  server:
    container_name: server
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.tests
    ports:
      - 50051:50051
    depends_on:
      - postgres-db
    volumes:
      - ${CERTS_PATH}:/certs:ro
    networks:
      - internal

  postgres-db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  database_postgres_test:

# Networks to be created to facilitate communication between containers
networks:
  internal:
    driver: bridge