name: Build and  Publish Docker
on:
  push:
    tags:
      - 'v*.*.*' ## will be the tag of docker image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1


      - name: Publish Server to Github Registry
        uses: docker/build-push-action@v1
        with:
          repository: aau-network-security/haaukins-store/server
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          tag_with_ref: true
          tag_with_sha: true

      - name: Publish server to dockerhub
        uses: docker/build-push-action@v1
        with:
          repository: aaunetworksecurity/haaukins-store
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_H_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true


      - name: prev_tag
        run: echo "::set-output name=prevtag::$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)"

      - name: current_tag
        run: echo "::set-output name=currenttag::$(git describe --tags --abbrev=0)"

      - name: Create Change Log
        run: |
          git --no-pager log --pretty=oneline ${{ steps.prev_tag.outputs.prevtag }}...${{ steps.current_tag.outputs.currenttag }} > changelog.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./changelog.txt
          draft: false
          prerelease: false
