name: Build and  Publish Docker
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
             dep ensure
          fi
      - name: Test
        run: |
          go build -o server .
          chmod +x ./server
          ./server &
          go test ./tests

        env:
          SSL_OFF: true
          CERT: ./certs/server.crt
          CERT_KEY: ./certs/server.key
          SIGNIN_KEY: random-signin-key


