name: Build and  Publish Docker
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, self-hosted]

    services:
      postgres:
        # pulling docker hub
        image: postgres:latest # same with the one which is written on docker-compose
        env:
          POSTGRES_PASSWORD: dummy-password
          POSTGRES_USER: dummy-user
          POSTGRES_DB: dummy-db
            # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
             dep ensure
          fi
      - name: Copy Certificates
        run: cp -r ./tests/certs /

      - name: Test
        run: |
          go build -o server .
          chmod +x ./server
          ./server &
          go test ./tests
        env:  # this is nasty list of env variables, make it pretty
          SSL_OFF: false  # which means ssl enabled
          AUTH_KEY: random-key
          CERTS_PATH: certs
          CERT: /certs/localhost_50051.crt
          CERT_KEY: /certs/localhost_50051.key
          CA : /certs/haaukins-store.com.crt
          SIGNIN_KEY: random-signin-key
          DATABASE_HOST: localhost
          DB_PORT: 5432
          POSTGRES_USER: dummy-user
          POSTGRES_PASSWORD: dummy-password
          POSTGRES_DB: dummy-db
          HOST: localhost:50051

      - name: Clean up certificates path
        run : rm -rf /certs

