name: Build and  Publish Docker
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    services:
      postgres:
        # pulling docker hub
        image: postgres:latest # same with the one which is written on docker-compose
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: dummydb
            # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Download example config file
        run: |
          curl -o config.yml https://gist.githubusercontent.com/mrtrkmn/cc5becf2d8413ea18c27a5bb2aa4106f/raw/2fc5b3fd415846f0b993a67d20d0094309f00698/config.yml

      - name: Download certs
        run: |
          curl -o haaukins-store.com.crt https://gist.githubusercontent.com/mrtrkmn/da480dd97f74c7a9581d6a69d5b2e984/raw/cbc2e338800d81a904c320999e44ec38b721ff5c/haaukins-store.com.crt
          curl -o localhost_50051.key    https://gist.githubusercontent.com/mrtrkmn/12132d60247e24041b954ee43d5e5cb1/raw/f18d0f0f96539fb424d1c463ec7e60ae8f846d0c/localhost_50051.key
          curl -o localhost_50051.crt    https://gist.githubusercontent.com/mrtrkmn/fc57419e46a859a031e11aa10b97c9e1/raw/109b1e64340c7394dcd9f7295969659d3cbc72af/localhost_50051.crt

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
             dep ensure
          fi

      - name: Build and Run Server
        run: |
          go build -o server .
          chmod +x ./server
          ./server &

      - name: Run Tests
        run: go test -v ./...
        env:
          CERT: ./../localhost_50051.crt
          CERT_KEY: ./../localhost_50051.key
          CA: ./../haaukins-store.com.crt

      - name: Teardown resources # more stuff could be added in the future
        run : |
          rm -rf config.yml
          rm -rf *.crt *.key
